name: Defold
markdown: kramdown
defaults:
    -
        scope:
            path: ""
            type: "manuals"
        values:
            layout: "manual"
    -
        scope:
            path: ""
            type: "faq"
        values:
            layout: "text"
    -
        scope:
            path: ""
            type: "tutorials"
        values:
            layout: "tutorial"
collections:
    manuals:
        output: true
    faq:
        output: true
    tutorials:
        output: true
kramdown:
    auto_ids: true
    parse_block_html: true
