name: Defold
markdown: kramdown
defaults:
    -
        scope:
            path: ""
            type: "manuals"
        values:
            layout: "manual"
    -
        scope:
            path: ""
            type: "faq"
        values:
            layout: "text"
    -
        scope:
            path: ""
            type: "tutorials"
        values:
            layout: "tutorial"
permalink: /:categories/:year/:month/:day/:title/
collections:
    manuals:
        output: true
    faq:
        output: true
    tutorials:
        output: true
    assets:
        output: true
    authors:
        output: true
kramdown:
    auto_ids: true
    parse_block_html: true
