name: Defold
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
collections:
    assets:
        output: true
    authors:
        output: true
    tags:
        output: true
kramdown:
    auto_ids: true
    parse_block_html: true
exclude:
    - update.py
    - README.md
    - serve.sh
    - Pipfile
    - Pipfile.lock
    - CNAME
