name: CI

on: [push]

jobs:
  update_stars:

    runs-on: ubuntu-latest
    
    steps: [
      { name: 'Checkout', uses: actions/checkout@v1, with: { fetch-depth: 1 } },
      { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x64 } },
      { name: 'Update stars', run: 'python update.py starcount' }]
